import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { getPriorityLevel, type Farmer } from "./types";

function downloadBlob(content: BlobPart, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function csvCell(v: unknown): string {
  const s = v == null ? "" : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function exportFarmersCSV(farmers: Farmer[]) {
  const headers = [
    "Name",
    "Location",
    "Phone",
    "Income",
    "Priority",
    "Cows",
    "Diseases",
    "Soil",
  ];
  const rows = farmers.map((f) => [
    f.name,
    f.location || "",
    f.phone || "",
    f.income ?? 0,
    `${getPriorityLevel(f.priority ?? 0)} (${f.priority ?? 0})`,
    (f.cows || []).join("; "),
    (f.diseases || []).join("; "),
    f.soil || "",
  ]);
  const csv = [headers, ...rows]
    .map((r) => r.map(csvCell).join(","))
    .join("\n");
  const ts = new Date().toISOString().slice(0, 10);
  downloadBlob(csv, `digicow-farmers-${ts}.csv`, "text/csv;charset=utf-8;");
}

export function exportFarmersPDF(farmers: Farmer[]) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Header band
  doc.setFillColor(20, 83, 45);
  doc.rect(0, 0, pageWidth, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("DigiCow AI - Farmers Report", 40, 35);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 40, 55);

  // Summary
  const total = farmers.length;
  const critical = farmers.filter((f) => (f.priority ?? 0) >= 75).length;
  const withDisease = farmers.filter((f) => (f.diseases || []).length > 0).length;

  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Summary", 40, 100);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Total Farmers: ${total}`, 40, 118);
  doc.text(`Critical Priority: ${critical}`, 180, 118);
  doc.text(`Active Disease Cases: ${withDisease}`, 340, 118);

  autoTable(doc, {
    startY: 140,
    head: [["Name", "Location", "Cows", "Diseases", "Priority"]],
    body: farmers.map((f) => [
      f.name,
      f.location || "—",
      (f.cows || []).join(", ") || "—",
      (f.diseases || []).join(", ") || "Healthy",
      `${getPriorityLevel(f.priority ?? 0)} (${f.priority ?? 0})`,
    ]),
    styles: { fontSize: 9, cellPadding: 6 },
    headStyles: { fillColor: [20, 83, 45], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 247, 245] },
    margin: { left: 40, right: 40 },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(
      "Generated by DigiCow AI - Kenya AI Challenge 2026",
      40,
      pageHeight - 20,
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 80, pageHeight - 20);
  }

  const ts = new Date().toISOString().slice(0, 10);
  doc.save(`digicow-farmers-${ts}.pdf`);
}
