/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmersAddRouteImport } from './routes/farmers.add'
import { Route as FarmersNameRouteImport } from './routes/farmers.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersAddRoute = FarmersAddRouteImport.update({
  id: '/farmers/add',
  path: '/farmers/add',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersNameRoute = FarmersNameRouteImport.update({
  id: '/farmers/$name',
  path: '/farmers/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farmers/$name': typeof FarmersNameRoute
  '/farmers/add': typeof FarmersAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/farmers/$name': typeof FarmersNameRoute
  '/farmers/add': typeof FarmersAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farmers/$name': typeof FarmersNameRoute
  '/farmers/add': typeof FarmersAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/farmers/$name' | '/farmers/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/farmers/$name' | '/farmers/add'
  id: '__root__' | '/' | '/farmers/$name' | '/farmers/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmersNameRoute: typeof FarmersNameRoute
  FarmersAddRoute: typeof FarmersAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers/add': {
      id: '/farmers/add'
      path: '/farmers/add'
      fullPath: '/farmers/add'
      preLoaderRoute: typeof FarmersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers/$name': {
      id: '/farmers/$name'
      path: '/farmers/$name'
      fullPath: '/farmers/$name'
      preLoaderRoute: typeof FarmersNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmersNameRoute: FarmersNameRoute,
  FarmersAddRoute: FarmersAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
